[2022-11-29T03:57:10.242+0000] {processor.py:154} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:57:10.248+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T03:57:10.250+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:10.250+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:57:15.375+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:15.375+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-xvzoy3s4 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T03:57:16.120+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:16.115+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T03:57:17.339+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:57:17.682+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:17.681+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T03:57:17.719+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:17.719+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T03:57:17.822+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 7.597 seconds
[2022-11-29T03:57:48.951+0000] {processor.py:154} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:57:48.955+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T03:57:48.968+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:48.968+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:57:55.908+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:55.908+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-axjn8jrg because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T03:57:56.089+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:56.089+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T03:57:56.490+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:57:56.563+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:56.562+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T03:57:56.593+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:57:56.593+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T03:57:56.617+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 7.704 seconds
[2022-11-29T03:58:28.660+0000] {processor.py:154} INFO - Started process (PID=110) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:58:28.677+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T03:58:28.687+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:28.687+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:58:53.612+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:53.612+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-covlzi_1 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T03:58:53.798+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:53.797+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T03:58:54.106+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:58:54.155+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:54.154+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T03:58:54.185+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:58:54.185+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T03:58:54.206+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 25.633 seconds
[2022-11-29T03:59:27.577+0000] {processor.py:154} INFO - Started process (PID=143) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:59:27.622+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T03:59:27.645+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:59:27.645+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T03:59:57.815+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:59:57.792+0000] {timeout.py:68} ERROR - Process timed out, PID: 143
[2022-11-29T04:00:00.251+0000] {logging_mixin.py:137} INFO - [2022-11-29T03:59:57.916+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py", line 22, in <module>
    from . import _stats
  File "_stats.pyx", line 1, in init scipy.stats._stats
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 143
[2022-11-29T04:00:01.117+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:00:03.165+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 37.094 seconds
[2022-11-29T04:01:04.786+0000] {processor.py:154} INFO - Started process (PID=186) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:01:04.875+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:01:04.963+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:01:04.962+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:01:35.664+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:01:35.302+0000] {timeout.py:68} ERROR - Process timed out, PID: 186
[2022-11-29T04:01:36.738+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:01:35.716+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 240, in <module>
    from . import csgraph
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csgraph/__init__.py", line 196, in <module>
    from ._reordering import reverse_cuthill_mckee, structural_rank
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 186
[2022-11-29T04:01:37.164+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:01:43.125+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 39.336 seconds
[2022-11-29T04:02:52.186+0000] {processor.py:154} INFO - Started process (PID=223) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:02:52.998+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:02:56.979+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:02:56.900+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:03:32.990+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:03:31.801+0000] {timeout.py:68} ERROR - Process timed out, PID: 223
[2022-11-29T04:03:55.064+0000] {processor.py:154} INFO - Started process (PID=238) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:03:55.572+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:03:55.968+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:03:55.965+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:04:28.590+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:04:27.794+0000] {timeout.py:68} ERROR - Process timed out, PID: 238
[2022-11-29T04:04:30.003+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:04:29.141+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 240, in <module>
    from . import csgraph
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csgraph/__init__.py", line 183, in <module>
    from ._shortest_path import (
  File "_shortest_path.pyx", line 17, in init scipy.sparse.csgraph._shortest_path
  File "<frozen importlib._bootstrap>", line 194, in _lock_unlock_module
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 238
[2022-11-29T04:04:30.796+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:04:38.717+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 44.869 seconds
[2022-11-29T04:04:59.615+0000] {processor.py:154} INFO - Started process (PID=242) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:05:00.584+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:05:02.109+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:05:01.788+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:05:34.626+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:05:34.237+0000] {timeout.py:68} ERROR - Process timed out, PID: 242
[2022-11-29T04:05:37.846+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:05:35.105+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/__init__.py", line 83, in <module>
    _fun = _deprecated(_msg.format(_key))(_fun)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/_lib/deprecation.py", line 16, in wrap
    @functools.wraps(fun)
  File "/usr/local/lib/python3.7/functools.py", line 60, in update_wrapper
    getattr(wrapper, attr).update(getattr(wrapped, attr, {}))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 242
[2022-11-29T04:05:41.077+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:06:09.101+0000] {processor.py:154} INFO - Started process (PID=244) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:06:10.369+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:06:11.445+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:06:11.050+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:06:43.248+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:06:42.717+0000] {timeout.py:68} ERROR - Process timed out, PID: 244
[2022-11-29T04:06:46.263+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:06:44.832+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 230, in <module>
    from .lil import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/lil.py", line 17, in <module>
    from . import _csparsetools
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 244
[2022-11-29T04:06:48.119+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:07:48.784+0000] {processor.py:154} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:07:49.502+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:07:50.099+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:07:49.972+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:08:22.459+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:08:22.088+0000] {timeout.py:68} ERROR - Process timed out, PID: 247
[2022-11-29T04:08:23.644+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:08:22.664+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 228, in <module>
    from .csr import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/csr.py", line 10, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 247
[2022-11-29T04:08:23.888+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:08:49.865+0000] {processor.py:154} INFO - Started process (PID=252) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:08:50.016+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:08:50.616+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:08:50.433+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:09:22.084+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:09:21.831+0000] {timeout.py:68} ERROR - Process timed out, PID: 252
[2022-11-29T04:09:25.249+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:09:22.210+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 252
[2022-11-29T04:09:26.332+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:12:27.980+0000] {processor.py:154} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:12:32.499+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:12:33.417+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:12:33.351+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:13:06.229+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:13:05.762+0000] {timeout.py:68} ERROR - Process timed out, PID: 255
[2022-11-29T04:13:49.129+0000] {processor.py:154} INFO - Started process (PID=258) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:13:50.285+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:13:57.883+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:13:51.988+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:14:30.609+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:14:29.562+0000] {timeout.py:68} ERROR - Process timed out, PID: 258
[2022-11-29T04:15:13.544+0000] {processor.py:154} INFO - Started process (PID=261) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:15:14.016+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:15:15.337+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:15:14.573+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:15:55.967+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:15:55.736+0000] {timeout.py:68} ERROR - Process timed out, PID: 261
[2022-11-29T04:16:36.048+0000] {processor.py:154} INFO - Started process (PID=264) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:16:37.730+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:16:40.685+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:16:39.981+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:17:16.716+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:17:15.596+0000] {timeout.py:68} ERROR - Process timed out, PID: 264
[2022-11-29T04:17:18.988+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:17:17.011+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/__init__.py", line 74, in <module>
    from ._lib.deprecation import _deprecated
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 527, in _compile_bytecode
  File "<frozen importlib._bootstrap>", line 224, in _verbose_message
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 264
[2022-11-29T04:17:22.377+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:18:08.882+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 95.989 seconds
[2022-11-29T04:18:31.133+0000] {processor.py:154} INFO - Started process (PID=266) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:18:32.677+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:18:33.075+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:18:33.021+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:19:05.815+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:05.090+0000] {timeout.py:68} ERROR - Process timed out, PID: 266
[2022-11-29T04:19:07.059+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:06.233+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 4, in <module>
    _warnings.simplefilter("ignore")
  File "/usr/local/lib/python3.7/warnings.py", line 175, in simplefilter
    assert action in ("error", "ignore", "always", "default", "module",
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 266
[2022-11-29T04:19:08.536+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:19:19.332+0000] {processor.py:154} INFO - Started process (PID=269) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:19:20.069+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:19:20.556+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:20.478+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:19:51.864+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:51.780+0000] {timeout.py:68} ERROR - Process timed out, PID: 269
[2022-11-29T04:19:56.457+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:19:51.948+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/__init__.py", line 18, in <module>
    from .backend.context import cpu_count
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/backend/__init__.py", line 2, in <module>
    from multiprocessing import synchronize
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 870, in get_code
  File "<frozen importlib._bootstrap_external>", line 542, in _code_to_timestamp_pyc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 269
[2022-11-29T04:20:00.083+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:39:15.280+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:39:15.296+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:39:15.304+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:15.303+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:39:19.837+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:19.836+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-b3e5ot8i because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T04:39:20.332+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:20.330+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T04:39:21.521+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:39:21.729+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:21.729+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T04:39:21.779+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:21.779+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T04:39:21.902+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 6.696 seconds
[2022-11-29T04:39:52.909+0000] {processor.py:154} INFO - Started process (PID=70) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:39:52.914+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:39:52.927+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:52.926+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:39:55.779+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:55.778+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-33duay2d because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T04:39:56.004+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:56.004+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T04:39:56.457+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:39:56.518+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:56.518+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T04:39:56.557+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:39:56.557+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T04:39:56.575+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 3.679 seconds
[2022-11-29T04:40:28.613+0000] {processor.py:154} INFO - Started process (PID=97) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:40:28.656+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:40:28.671+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:40:28.671+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:40:59.341+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:40:59.161+0000] {timeout.py:68} ERROR - Process timed out, PID: 97
[2022-11-29T04:41:01.259+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:41:00.339+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py", line 32, in <module>
    import scipy.stats._boost as _boost
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_boost/__init__.py", line 7, in <module>
    from scipy.stats._boost.binom_ufunc import (
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 97
[2022-11-29T04:41:39.359+0000] {processor.py:154} INFO - Started process (PID=137) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:41:39.417+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:41:39.432+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:41:39.431+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:42:09.836+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:42:09.696+0000] {timeout.py:68} ERROR - Process timed out, PID: 137
[2022-11-29T04:42:10.653+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:42:09.858+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py", line 2915, in <module>
    gengamma = gengamma_gen(a=0.0, name='gengamma')
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1721, in __init__
    self._attach_methods()
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 1756, in _attach_methods
    self._attach_argparser_methods()
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 708, in _attach_argparser_methods
    exec(self._parse_arg_template, ns)
  File "<string>", line 2, in <module>
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 137
[2022-11-29T04:42:11.971+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:42:59.130+0000] {processor.py:154} INFO - Started process (PID=179) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:43:00.248+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:43:00.576+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:43:00.549+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:43:53.809+0000] {processor.py:154} INFO - Started process (PID=201) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:43:53.828+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:43:53.844+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:43:53.843+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:45:05.426+0000] {processor.py:154} INFO - Started process (PID=244) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:45:05.450+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:45:05.480+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:45:05.471+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:46:11.202+0000] {processor.py:154} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:46:11.270+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:46:11.343+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:46:11.340+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:46:41.533+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:46:41.495+0000] {timeout.py:68} ERROR - Process timed out, PID: 276
[2022-11-29T04:46:41.770+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:46:41.598+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 447, in <module>
    from . import mstats
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 327, in __exit__
  File "<frozen importlib._bootstrap>", line 222, in _verbose_message
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 276
[2022-11-29T04:46:41.820+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:46:43.355+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 32.537 seconds
[2022-11-29T04:48:04.153+0000] {processor.py:154} INFO - Started process (PID=298) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:48:04.167+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:48:04.171+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:48:04.171+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:48:35.093+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:48:35.018+0000] {timeout.py:68} ERROR - Process timed out, PID: 298
[2022-11-29T04:48:35.818+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:48:35.110+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 401, in <module>
    from ._minimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 30, in <module>
    from .lbfgsb import _minimize_lbfgsb
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 38, in <module>
    from . import _lbfgsb
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 298
[2022-11-29T04:48:36.175+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:48:38.251+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 34.334 seconds
[2022-11-29T04:49:11.122+0000] {processor.py:154} INFO - Started process (PID=338) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:49:11.244+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:49:11.328+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:49:11.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:50:02.912+0000] {processor.py:154} INFO - Started process (PID=364) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:50:02.938+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:50:02.979+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:50:02.964+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:50:57.213+0000] {processor.py:154} INFO - Started process (PID=398) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:50:57.233+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:50:57.238+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:50:57.237+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:51:39.099+0000] {processor.py:154} INFO - Started process (PID=422) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:51:39.104+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:51:39.107+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:51:39.106+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:52:17.338+0000] {processor.py:154} INFO - Started process (PID=444) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:52:17.362+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:52:17.377+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:52:17.377+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:52:51.242+0000] {processor.py:154} INFO - Started process (PID=456) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:52:51.255+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:52:51.263+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:52:51.262+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:53:53.031+0000] {processor.py:154} INFO - Started process (PID=487) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:53:53.056+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:53:53.061+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:53:53.060+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:54:24.537+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:54:23.828+0000] {timeout.py:68} ERROR - Process timed out, PID: 487
[2022-11-29T04:54:27.356+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:54:25.050+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 413, in <module>
    from ._linprog import linprog, linprog_verbose_callback
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_linprog.py", line 23, in <module>
    from ._linprog_ip import _linprog_ip
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_linprog_ip.py", line 27, in <module>
    from ._linprog_util import _postsolve
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 487
[2022-11-29T04:54:31.346+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:55:27.077+0000] {processor.py:154} INFO - Started process (PID=524) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T04:55:30.986+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T04:55:33.291+0000] {logging_mixin.py:137} INFO - [2022-11-29T04:55:32.884+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:06:38.650+0000] {processor.py:154} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:06:38.658+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:06:38.660+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:06:38.660+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:07:38.674+0000] {processor.py:154} INFO - Started process (PID=83) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:07:38.681+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:07:38.692+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:38.692+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:07:47.240+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:47.237+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-i1r7322p because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T05:07:48.098+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:48.096+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T05:07:49.575+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:07:49.847+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:49.847+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T05:07:49.925+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:07:49.925+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T05:07:50.092+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 11.452 seconds
[2022-11-29T05:08:23.269+0000] {processor.py:154} INFO - Started process (PID=121) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:08:23.317+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:08:23.359+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:08:23.358+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:08:53.610+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:08:53.479+0000] {timeout.py:68} ERROR - Process timed out, PID: 121
[2022-11-29T05:08:53.913+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:08:53.687+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 428, in <module>
    test = PytestTester(__name__)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/_lib/_testutils.py", line 25, in __init__
    self.module_name = module_name
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 121
[2022-11-29T05:08:54.222+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:08:54.736+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 31.555 seconds
[2022-11-29T05:09:26.158+0000] {processor.py:154} INFO - Started process (PID=163) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:09:26.197+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:09:26.237+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:09:26.236+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:10:25.735+0000] {processor.py:154} INFO - Started process (PID=197) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:10:25.809+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:10:25.822+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:10:25.822+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:11:35.450+0000] {processor.py:154} INFO - Started process (PID=237) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:11:35.516+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:11:35.631+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:11:35.610+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:12:08.624+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:12:05.824+0000] {timeout.py:68} ERROR - Process timed out, PID: 237
[2022-11-29T05:12:14.511+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:12:13.577+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 27, in <module>
    from scipy import integrate
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/integrate/__init__.py", line 95, in <module>
    from ._ivp import (solve_ivp, OdeSolution, DenseOutput,
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/integrate/_ivp/__init__.py", line 2, in <module>
    from .ivp import solve_ivp
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/integrate/_ivp/ivp.py", line 5, in <module>
    from .rk import RK23, RK45, DOP853
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/integrate/_ivp/rk.py", line 5, in <module>
    from . import dop853_coefficients
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/integrate/_ivp/dop853_coefficients.py", line 28, in <module>
    A[2, 1] = 5.91751709536136983633785987549e-2
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 237
[2022-11-29T05:12:16.119+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:12:23.731+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 48.764 seconds
[2022-11-29T05:13:46.224+0000] {processor.py:154} INFO - Started process (PID=279) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:13:47.724+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:13:48.567+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:13:48.439+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:14:32.844+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:14:22.980+0000] {timeout.py:68} ERROR - Process timed out, PID: 279
[2022-11-29T05:14:40.426+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:14:36.859+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 53, in <module>
    os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "True")
  File "/usr/local/lib/python3.7/os.py", line 718, in setdefault
    self[key] = value
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 279
[2022-11-29T05:14:54.592+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:16:33.672+0000] {processor.py:154} INFO - Started process (PID=310) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:16:51.692+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:16:54.922+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:16:53.389+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:17:36.033+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:17:35.913+0000] {timeout.py:68} ERROR - Process timed out, PID: 310
[2022-11-29T05:17:57.945+0000] {processor.py:154} INFO - Started process (PID=345) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:17:58.258+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:17:59.979+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:17:59.038+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:18:33.611+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:18:33.028+0000] {timeout.py:68} ERROR - Process timed out, PID: 345
[2022-11-29T05:18:41.788+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:18:34.485+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 345
[2022-11-29T05:18:47.734+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:20:29.231+0000] {processor.py:154} INFO - Started process (PID=359) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:20:35.880+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:20:37.674+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:20:37.200+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:25:04.232+0000] {processor.py:154} INFO - Started process (PID=431) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:25:05.245+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:25:06.627+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:25:06.032+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:26:39.995+0000] {processor.py:154} INFO - Started process (PID=481) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:26:41.541+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:26:46.808+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:26:46.378+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:27:23.361+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:27:21.911+0000] {timeout.py:68} ERROR - Process timed out, PID: 481
[2022-11-29T05:27:27.424+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:27:24.905+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 481
[2022-11-29T05:27:31.286+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:28:15.181+0000] {processor.py:154} INFO - Started process (PID=517) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T05:28:17.389+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T05:28:23.387+0000] {logging_mixin.py:137} INFO - [2022-11-29T05:28:22.774+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:01:13.279+0000] {processor.py:154} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:01:13.283+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:01:13.286+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:13.285+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:01:22.196+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:22.185+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ts6pyrg2 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:01:23.621+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:23.620+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:01:27.168+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:01:29.747+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:29.670+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:01:30.095+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:01:30.095+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T07:01:30.239+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 16.974 seconds
[2022-11-29T07:02:09.597+0000] {processor.py:154} INFO - Started process (PID=70) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:02:09.623+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:02:09.742+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:09.666+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:02:16.378+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:16.377+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-sea_qljn because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:02:16.616+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:16.615+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:02:16.978+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:02:17.048+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:17.048+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:02:17.079+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:17.079+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T07:02:17.101+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 9.522 seconds
[2022-11-29T07:02:48.580+0000] {processor.py:154} INFO - Started process (PID=99) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:02:48.588+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:02:48.596+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:02:48.593+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:03:07.751+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:07.751+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-xujs9rne because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:03:07.945+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:07.944+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:03:08.321+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:03:08.399+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:08.399+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:03:08.426+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:08.426+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T07:03:08.442+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 19.916 seconds
[2022-11-29T07:03:40.189+0000] {processor.py:154} INFO - Started process (PID=144) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:03:40.197+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:03:40.207+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:40.207+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:03:45.375+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:45.374+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9nm3r9rp because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:03:45.749+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:45.749+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:03:46.280+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:03:46.362+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:46.362+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:03:46.392+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:03:46.392+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T07:03:46.408+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 6.279 seconds
[2022-11-29T07:04:17.447+0000] {processor.py:154} INFO - Started process (PID=164) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:04:17.476+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:04:17.480+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:17.480+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:04:26.291+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:26.291+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-4w3osah7 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T07:04:26.483+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:26.482+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T07:04:26.822+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:04:26.865+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:26.864+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T07:04:26.895+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:26.895+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T07:04:26.911+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 9.569 seconds
[2022-11-29T07:04:57.588+0000] {processor.py:154} INFO - Started process (PID=201) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:04:57.592+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:04:57.597+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:04:57.597+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:05:32.340+0000] {processor.py:154} INFO - Started process (PID=225) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:05:32.373+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:05:32.378+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:05:32.377+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:06:17.335+0000] {processor.py:154} INFO - Started process (PID=250) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:06:17.478+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:06:17.534+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:06:17.526+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:06:57.885+0000] {processor.py:154} INFO - Started process (PID=272) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:06:57.895+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:06:57.904+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:06:57.904+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:07:43.854+0000] {processor.py:154} INFO - Started process (PID=297) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:07:43.863+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:07:43.874+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:07:43.873+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:08:03.201+0000] {processor.py:154} INFO - Started process (PID=308) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:08:03.231+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:08:03.242+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:08:03.242+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:08:20.960+0000] {processor.py:154} INFO - Started process (PID=321) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:08:20.972+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:08:20.976+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:08:20.976+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:08:55.392+0000] {processor.py:154} INFO - Started process (PID=340) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:08:55.419+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:08:55.422+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:08:55.421+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:09:34.558+0000] {processor.py:154} INFO - Started process (PID=363) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:09:34.587+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:09:34.601+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:09:34.600+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:10:20.187+0000] {processor.py:154} INFO - Started process (PID=389) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:10:20.606+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:10:20.974+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:10:20.840+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:11:03.911+0000] {processor.py:154} INFO - Started process (PID=415) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:11:03.925+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:11:03.928+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:11:03.928+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:11:46.820+0000] {processor.py:154} INFO - Started process (PID=437) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:11:46.866+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:11:46.870+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:11:46.870+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:12:07.597+0000] {processor.py:154} INFO - Started process (PID=448) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:12:07.619+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:12:07.625+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:12:07.624+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:12:53.982+0000] {processor.py:154} INFO - Started process (PID=476) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:12:54.005+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:12:54.036+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:12:54.036+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:13:36.395+0000] {processor.py:154} INFO - Started process (PID=500) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:13:36.410+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:13:36.420+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:13:36.420+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:14:13.732+0000] {processor.py:154} INFO - Started process (PID=524) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:14:13.751+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:14:13.755+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:14:13.755+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:16:57.630+0000] {processor.py:154} INFO - Started process (PID=544) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:16:57.642+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:16:57.653+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:16:57.653+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:17:27.912+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:17:27.871+0000] {timeout.py:68} ERROR - Process timed out, PID: 544
[2022-11-29T07:17:28.475+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:17:28.140+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/__init__.py", line 101, in <module>
    from ._procrustes import procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/spatial/_procrustes.py", line 9, in <module>
    from scipy.linalg import orthogonal_procrustes
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/__init__.py", line 196, in <module>
    from .basic import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/basic.py", line 10, in <module>
    from .flinalg import get_flinalg_funcs
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/linalg/flinalg.py", line 11, in <module>
    from . import _flinalg
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 544
[2022-11-29T07:17:28.690+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:17:33.195+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 35.657 seconds
[2022-11-29T07:18:14.516+0000] {processor.py:154} INFO - Started process (PID=587) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:18:14.616+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:18:15.195+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:18:15.002+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:18:46.676+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:18:46.119+0000] {timeout.py:68} ERROR - Process timed out, PID: 587
[2022-11-29T07:18:51.643+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:18:46.992+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/__init__.py", line 18, in <module>
    from .backend.context import cpu_count
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/backend/__init__.py", line 4, in <module>
    from .context import get_context
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/backend/context.py", line 22, in <module>
    from .process import LokyProcess, LokyInitMainProcess
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 587
[2022-11-29T07:18:52.391+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:18:58.011+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 43.842 seconds
[2022-11-29T07:19:36.206+0000] {processor.py:154} INFO - Started process (PID=617) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:19:37.255+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:19:39.325+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:19:38.718+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:20:13.852+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:20:11.135+0000] {timeout.py:68} ERROR - Process timed out, PID: 617
[2022-11-29T07:20:20.227+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:20:15.786+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/__init__.py", line 153, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "_ccallback_c.pyx", line 215, in init scipy._lib._ccallback_c
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 73, in CFUNCTYPE
    def CFUNCTYPE(restype, *argtypes, **kw):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 617
[2022-11-29T07:20:21.472+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:20:53.189+0000] {processor.py:154} INFO - Started process (PID=652) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:20:53.297+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:20:53.428+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:20:53.427+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:21:24.428+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:21:23.978+0000] {timeout.py:68} ERROR - Process timed out, PID: 652
[2022-11-29T07:21:29.351+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:21:24.716+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 231, in <module>
    from .dok import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 652
[2022-11-29T07:21:31.355+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:34:24.222+0000] {processor.py:154} INFO - Started process (PID=713) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:34:26.180+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:34:27.807+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:34:27.549+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:35:04.367+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:35:02.312+0000] {timeout.py:68} ERROR - Process timed out, PID: 713
[2022-11-29T07:35:10.912+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:35:09.247+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 713
[2022-11-29T07:35:11.637+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:35:32.471+0000] {processor.py:154} INFO - Started process (PID=734) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:35:33.485+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T07:35:33.788+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:35:33.787+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T07:36:16.916+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:36:11.676+0000] {timeout.py:68} ERROR - Process timed out, PID: 734
[2022-11-29T07:52:18.012+0000] {logging_mixin.py:137} INFO - [2022-11-29T07:52:12.836+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/__init__.py", line 18, in <module>
    from .backend.context import cpu_count
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/externals/loky/backend/__init__.py", line 2, in <module>
    from multiprocessing import synchronize
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 734
[2022-11-29T07:52:33.496+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T09:41:57.162+0000] {processor.py:154} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T09:41:57.277+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T09:41:57.311+0000] {logging_mixin.py:137} INFO - [2022-11-29T09:41:57.311+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T09:42:28.183+0000] {logging_mixin.py:137} INFO - [2022-11-29T09:42:27.575+0000] {timeout.py:68} ERROR - Process timed out, PID: 98
[2022-11-29T09:42:28.877+0000] {logging_mixin.py:137} INFO - [2022-11-29T09:42:28.443+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 20, in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/string_arrow.py", line 65, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 18, in <module>
    from pyarrow._compute import (  # noqa
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 98
[2022-11-29T09:42:29.097+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T09:42:31.345+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 34.532 seconds
[2022-11-29T16:30:14.050+0000] {processor.py:154} INFO - Started process (PID=135) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:30:14.173+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:30:14.214+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:30:14.213+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:30:44.672+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:30:44.350+0000] {timeout.py:68} ERROR - Process timed out, PID: 135
[2022-11-29T16:30:44.932+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:30:44.717+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 64, in <module>
    from pandas.core.aggregation import (
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 135
[2022-11-29T16:30:45.153+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:30:47.067+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 33.195 seconds
[2022-11-29T16:31:24.750+0000] {processor.py:154} INFO - Started process (PID=173) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:31:24.784+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:31:24.797+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:31:24.797+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:32:31.951+0000] {processor.py:154} INFO - Started process (PID=199) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:32:32.040+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:32:32.106+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:32:32.106+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:33:03.128+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:33:02.518+0000] {timeout.py:68} ERROR - Process timed out, PID: 199
[2022-11-29T16:33:04.817+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:33:03.307+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 400, in <module>
    from .optimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_numdiff.py", line 6, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/linalg/__init__.py", line 111, in <module>
    from .isolve import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/linalg/isolve/__init__.py", line 7, in <module>
    from .lsqr import lsqr
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 199
[2022-11-29T16:33:07.173+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:40:22.713+0000] {processor.py:154} INFO - Started process (PID=68) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:40:23.330+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:40:23.364+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:40:23.357+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:40:54.658+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:40:53.880+0000] {timeout.py:68} ERROR - Process timed out, PID: 68
[2022-11-29T16:40:57.622+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:40:56.942+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 401, in <module>
    from ._minimize import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 24, in <module>
    from ._trustregion_ncg import _minimize_trust_ncg
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1364, in find_spec
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 68
[2022-11-29T16:40:57.717+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:40:59.338+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 36.723 seconds
[2022-11-29T16:41:36.121+0000] {processor.py:154} INFO - Started process (PID=95) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:41:36.198+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:41:36.222+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:41:36.212+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:42:06.542+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:42:06.411+0000] {timeout.py:68} ERROR - Process timed out, PID: 95
[2022-11-29T16:42:07.082+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:42:06.636+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 2, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/compat.pxi", line 49, in init pyarrow.lib
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/__init__.py", line 2, in <module>
    from cloudpickle.cloudpickle_fast import CloudPickler, dumps, dump  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 540, in <module>
    class CloudPickler(Pickler):
  File "/home/airflow/.local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 734, in CloudPickler
    dispatch = Pickler.dispatch.copy()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 95
[2022-11-29T16:42:07.231+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:42:12.023+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 36.137 seconds
[2022-11-29T16:42:50.338+0000] {processor.py:154} INFO - Started process (PID=137) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:42:50.465+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:42:50.624+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:42:50.623+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:49:04.889+0000] {processor.py:154} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:49:04.895+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:49:04.898+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:04.898+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:49:08.035+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:08.034+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-1r1jhvhq because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T16:49:08.630+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:08.629+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T16:49:09.575+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:49:09.760+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:09.759+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T16:49:09.813+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:09.813+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T16:49:09.860+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 4.997 seconds
[2022-11-29T16:49:56.435+0000] {processor.py:154} INFO - Started process (PID=70) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:49:56.520+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:49:56.589+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:49:56.581+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:50:26.725+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:50:26.705+0000] {timeout.py:68} ERROR - Process timed out, PID: 70
[2022-11-29T16:50:26.909+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:50:26.737+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 27, in <module>
    from scipy import integrate
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/integrate/__init__.py", line 92, in <module>
    from .quadpack import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 70
[2022-11-29T16:50:27.016+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:51:04.062+0000] {processor.py:154} INFO - Started process (PID=105) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:51:04.066+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:51:04.071+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:04.071+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:51:05.879+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:05.878+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ct43m84n because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T16:51:06.444+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:06.443+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T16:51:07.594+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:51:07.881+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:07.880+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T16:51:07.925+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:07.925+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T16:51:07.967+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 3.914 seconds
[2022-11-29T16:51:38.587+0000] {processor.py:154} INFO - Started process (PID=131) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:51:39.534+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:51:39.709+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:39.709+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:51:49.559+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:49.559+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-37nqz1qv because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-29T16:51:49.830+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:49.830+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-29T16:51:50.470+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_preparator_dag']) retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:51:50.535+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:50.535+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-29T16:51:50.572+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:51:50.571+0000] {dag.py:3340} INFO - Setting next_dagrun for data_preparator_dag to 2022-11-27T00:00:00+00:00, run_after=2022-12-04T00:00:00+00:00
[2022-11-29T16:51:50.602+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 12.199 seconds
[2022-11-29T16:52:22.129+0000] {processor.py:154} INFO - Started process (PID=167) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:52:22.179+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:52:22.209+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:52:22.208+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:52:52.754+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:52:52.599+0000] {timeout.py:68} ERROR - Process timed out, PID: 167
[2022-11-29T16:52:57.226+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:52:53.045+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_memmapping_reducer.py", line 8, in <module>
    from mmap import mmap
  File "<frozen importlib._bootstrap>", line 1009, in _handle_fromlist
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 167
[2022-11-29T16:52:57.492+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:52:58.331+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 36.399 seconds
[2022-11-29T16:53:32.082+0000] {processor.py:154} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:53:32.189+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:53:32.230+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:53:32.222+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:54:02.485+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:54:02.382+0000] {timeout.py:68} ERROR - Process timed out, PID: 187
[2022-11-29T16:54:02.762+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:54:02.518+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 44, in <module>
    from . import mstats_basic
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 187
[2022-11-29T16:54:02.813+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:54:04.458+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 32.646 seconds
[2022-11-29T16:54:46.319+0000] {processor.py:154} INFO - Started process (PID=194) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:54:46.500+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:54:46.611+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:54:46.597+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:55:17.241+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:55:16.899+0000] {timeout.py:68} ERROR - Process timed out, PID: 194
[2022-11-29T16:55:18.565+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:55:17.484+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/model_selection/__init__.py", line 23, in <module>
    from ._validation import cross_val_score
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 31, in <module>
    from ..metrics import check_scoring
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from ._ranking import auc
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 35, in <module>
    from ..utils.sparsefuncs import count_nonzero
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 194
[2022-11-29T16:55:19.149+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:55:24.654+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 38.822 seconds
[2022-11-29T16:56:18.297+0000] {processor.py:154} INFO - Started process (PID=199) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:56:18.331+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:56:18.353+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:56:18.353+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:57:20.364+0000] {processor.py:154} INFO - Started process (PID=219) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:57:20.457+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:57:20.472+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:57:20.468+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:57:50.654+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:57:50.608+0000] {timeout.py:68} ERROR - Process timed out, PID: 219
[2022-11-29T16:57:51.230+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:57:50.698+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 413, in <module>
    from ._linprog import linprog, linprog_verbose_callback
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/_linprog.py", line 23, in <module>
    from ._linprog_ip import _linprog_ip
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 219
[2022-11-29T16:57:53.822+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:58:25.292+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 65.399 seconds
[2022-11-29T16:58:37.471+0000] {processor.py:154} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:58:37.735+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T16:58:37.779+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:58:37.778+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T16:59:13.449+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:59:08.890+0000] {timeout.py:68} ERROR - Process timed out, PID: 248
[2022-11-29T16:59:24.755+0000] {logging_mixin.py:137} INFO - [2022-11-29T16:59:14.020+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 227, in <module>
    from .base import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/base.py", line 4, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/sputils.py", line 8, in <module>
    from scipy._lib._util import prod
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/_lib/_util.py", line 346, in <module>
    'kwonlyargs', 'kwonlydefaults', 'annotations'])
  File "/usr/local/lib/python3.7/collections/__init__.py", line 397, in namedtuple
    exec(s, namespace)
  File "<string>", line 1, in <module>
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 248
[2022-11-29T16:59:25.664+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:00:12.001+0000] {processor.py:154} INFO - Started process (PID=269) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:00:17.968+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T17:00:19.554+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:00:18.728+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:00:53.536+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:00:52.426+0000] {timeout.py:68} ERROR - Process timed out, PID: 269
[2022-11-29T17:01:27.017+0000] {processor.py:154} INFO - Started process (PID=280) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:01:27.761+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T17:01:28.548+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:01:28.537+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:01:59.771+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:01:59.605+0000] {timeout.py:68} ERROR - Process timed out, PID: 280
[2022-11-29T17:02:01.546+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:02:00.219+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/memory.py", line 32, in <module>
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_store_backends.py", line 17, in <module>
    from . import numpy_pickle
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 13, in <module>
    from .compressor import lz4, LZ4_NOT_INSTALLED_ERROR
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 589, in module_from_spec
  File "<frozen importlib._bootstrap>", line 568, in _init_module_attrs
  File "<frozen importlib._bootstrap>", line 409, in cached
  File "<frozen importlib._bootstrap_external>", line 372, in _get_cached
  File "<frozen importlib._bootstrap_external>", line 313, in cache_from_source
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 280
[2022-11-29T17:02:02.902+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:02:34.825+0000] {processor.py:154} INFO - Started process (PID=305) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:02:34.975+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T17:02:35.128+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:02:35.060+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:03:08.647+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:03:07.263+0000] {timeout.py:68} ERROR - Process timed out, PID: 305
[2022-11-29T17:03:17.863+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:03:10.228+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 21, in <module>
    from scipy.sparse import issparse
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/sparse/__init__.py", line 236, in <module>
    from .extract import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1394, in find_spec
  File "<frozen importlib._bootstrap_external>", line 95, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 87, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 81, in _path_stat
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 305
[2022-11-29T17:03:20.211+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:03:30.959+0000] {processor.py:154} INFO - Started process (PID=333) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:03:31.228+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T17:03:31.320+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:03:31.319+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:04:02.743+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:04:02.361+0000] {timeout.py:68} ERROR - Process timed out, PID: 333
[2022-11-29T17:04:04.876+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:04:03.217+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from . import _joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/memory.py", line 32, in <module>
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/_store_backends.py", line 17, in <module>
    from . import numpy_pickle
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 18, in <module>
    from .numpy_pickle_utils import Unpickler, Pickler
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 333
[2022-11-29T17:04:06.070+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:04:30.881+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_train_process.py took 59.825 seconds
[2022-11-29T17:05:18.115+0000] {processor.py:154} INFO - Started process (PID=365) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:05:18.690+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T17:05:19.146+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:05:19.130+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:06:38.261+0000] {processor.py:154} INFO - Started process (PID=401) to work on /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:06:40.868+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_train_process.py for tasks to queue
[2022-11-29T17:06:43.713+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:06:43.365+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_train_process.py
[2022-11-29T17:07:30.069+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:07:20.345+0000] {timeout.py:68} ERROR - Process timed out, PID: 401
[2022-11-29T17:07:36.449+0000] {logging_mixin.py:137} INFO - [2022-11-29T17:07:31.776+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_train_process.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_train_process.py", line 4, in <module>
    from packages.training_process import prepare_data, splitter, trainer, plotter
  File "/opt/airflow/dags/packages/training_process.py", line 1, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 21, in <module>
    from ._config import get_config, set_config, config_context
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_train_process.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 401
[2022-11-29T17:07:39.496+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_train_process.py
