[2022-11-30T12:25:07.867+0000] {processor.py:154} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:25:07.888+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:25:07.895+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:25:07.895+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:25:58.372+0000] {processor.py:154} INFO - Started process (PID=79) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:25:58.400+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:25:58.408+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:25:58.407+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:26:05.923+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:26:05.923+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ofluby_4 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-30T12:26:06.147+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:26:06.147+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-30T12:26:06.512+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:26:06.601+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:26:06.601+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-30T12:26:06.626+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:26:06.625+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-29T00:00:00+00:00, run_after=2022-11-30T00:00:00+00:00
[2022-11-30T12:26:06.646+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 8.290 seconds
[2022-11-30T12:26:38.341+0000] {processor.py:154} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:26:38.389+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:26:38.864+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:26:38.544+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:27:18.125+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:27:18.120+0000] {timeout.py:68} ERROR - Process timed out, PID: 112
[2022-11-30T12:27:18.228+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:27:18.156+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 4, in <module>
    from packages.ft_perceptron import *
  File "/opt/airflow/dags/packages/ft_perceptron.py", line 2, in <module>
    from packages.source.net import NN, Linear, Relu
  File "/opt/airflow/dags/packages/source/net.py", line 4, in <module>
    from sklearn.preprocessing import MinMaxScaler
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/__init__.py", line 28, in <module>
    from .fixes import np_version, parse_version
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 20, in <module>
    import scipy.stats
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/airflow/.local/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 400, in <module>
    from .optimize import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 112
[2022-11-30T12:27:18.238+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:27:18.380+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 40.294 seconds
[2022-11-30T12:27:50.276+0000] {processor.py:154} INFO - Started process (PID=152) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:27:50.289+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:27:50.299+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:27:50.298+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:28:21.047+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:28:21.019+0000] {timeout.py:68} ERROR - Process timed out, PID: 152
[2022-11-30T12:28:21.070+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0xffff9a1d0e60>
[2022-11-30T12:28:21.078+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2022-11-30T12:28:21.079+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/weakref.py", line 358, in remove
[2022-11-30T12:28:21.080+0000] {logging_mixin.py:137} WARNING -     def remove(k, selfref=ref(self)):
[2022-11-30T12:28:21.081+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2022-11-30T12:28:21.083+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2022-11-30T12:28:21.085+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 152
[2022-11-30T12:28:23.342+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:28:23.322+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ob7rjpat because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-30T12:28:23.907+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:28:23.906+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-30T12:28:25.033+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:28:25.431+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:28:25.430+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-30T12:28:25.512+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:28:25.511+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-30T00:00:00+00:00, run_after=2022-12-01T00:00:00+00:00
[2022-11-30T12:28:25.608+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 35.863 seconds
[2022-11-30T12:29:00.170+0000] {processor.py:154} INFO - Started process (PID=189) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:29:00.262+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:29:00.301+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:29:00.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:29:33.003+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:29:31.184+0000] {timeout.py:68} ERROR - Process timed out, PID: 189
[2022-11-30T12:29:34.289+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:29:33.210+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 64, in <module>
    from pandas.core.aggregation import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/aggregation.py", line 33, in <module>
    from pandas.core.indexes.api import Index
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/api.py", line 20, in <module>
    from pandas.core.indexes.interval import IntervalIndex
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/interval.py", line 86, in <module>
    from pandas.core.indexes.multi import MultiIndex
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 189
[2022-11-30T12:29:34.493+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:29:35.040+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 35.934 seconds
[2022-11-30T12:30:05.913+0000] {processor.py:154} INFO - Started process (PID=221) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:30:05.930+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:30:05.936+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:30:05.935+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:30:17.155+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:30:17.154+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-28aw434i because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-30T12:30:17.440+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:30:17.440+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-30T12:30:17.960+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:30:18.077+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:30:18.075+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-30T12:30:18.103+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:30:18.103+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-30T00:00:00+00:00, run_after=2022-12-01T00:00:00+00:00
[2022-11-30T12:30:18.145+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 12.272 seconds
[2022-11-30T12:30:50.923+0000] {processor.py:154} INFO - Started process (PID=259) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:30:51.002+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:30:51.024+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:30:51.023+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:31:21.722+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:31:21.228+0000] {timeout.py:68} ERROR - Process timed out, PID: 259
[2022-11-30T12:31:22.002+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:31:21.780+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 20, in <module>
    from pandas.core.arrays.string_arrow import ArrowStringArray
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/string_arrow.py", line 65, in <module>
    import pyarrow.compute as pc
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 251, in <module>
    _make_global_functions()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 248, in _make_global_functions
    g[cpp_name] = g[name] = _wrap_function(name, func)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 227, in _wrap_function
    return _decorate_compute_function(wrapper, name, func, option_class)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/compute.py", line 109, in _decorate_compute_function
    """.format(summary))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 259
[2022-11-30T12:31:22.149+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:31:27.321+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 36.451 seconds
[2022-11-30T12:31:59.703+0000] {processor.py:154} INFO - Started process (PID=292) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:31:59.723+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:31:59.729+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:31:59.728+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:32:45.887+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:32:45.862+0000] {timeout.py:68} ERROR - Process timed out, PID: 292
[2022-11-30T12:32:45.911+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0xffff9a1d0e60>
[2022-11-30T12:32:45.920+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2022-11-30T12:32:45.928+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/weakref.py", line 358, in remove
[2022-11-30T12:32:45.951+0000] {logging_mixin.py:137} WARNING -     def remove(k, selfref=ref(self)):
[2022-11-30T12:32:45.970+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2022-11-30T12:32:45.990+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2022-11-30T12:32:45.999+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 292
[2022-11-30T12:32:59.985+0000] {processor.py:154} INFO - Started process (PID=326) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:32:59.991+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:33:00.000+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:32:59.998+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:33:01.894+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:33:01.893+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ds4plgw2 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-30T12:33:02.096+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:33:02.096+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-30T12:33:02.723+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:33:02.910+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:33:02.909+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-30T12:33:02.940+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:33:02.940+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-30T00:00:00+00:00, run_after=2022-12-01T00:00:00+00:00
[2022-11-30T12:33:02.964+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 2.989 seconds
[2022-11-30T12:33:51.815+0000] {processor.py:154} INFO - Started process (PID=359) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:33:51.835+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:33:51.840+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:33:51.839+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:35:08.801+0000] {processor.py:154} INFO - Started process (PID=403) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:35:08.833+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:35:08.866+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:35:08.865+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:35:24.892+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:35:24.889+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-8j99r7nb because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-30T12:35:26.607+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:35:26.586+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-30T12:35:30.357+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:35:30.724+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:35:30.723+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-30T12:35:30.855+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:35:30.854+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-30T00:00:00+00:00, run_after=2022-12-01T00:00:00+00:00
[2022-11-30T12:35:30.932+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 22.682 seconds
[2022-11-30T12:36:02.279+0000] {processor.py:154} INFO - Started process (PID=441) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:36:02.297+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:36:02.301+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:36:02.301+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:36:33.036+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:36:32.849+0000] {timeout.py:68} ERROR - Process timed out, PID: 441
[2022-11-30T12:36:33.765+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:36:33.146+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 7, in <module>
    from pandas.core.arrays.categorical import Categorical
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 113, in <module>
    from pandas.core.strings.object_array import ObjectStringArrayMixin
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/object_array.py", line 24, in <module>
    class ObjectStringArrayMixin(BaseStringArrayMethods):
  File "/usr/local/lib/python3.7/abc.py", line 127, in __new__
    _abc_init(cls)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 441
[2022-11-30T12:36:34.189+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:36:38.141+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 35.785 seconds
[2022-11-30T12:37:09.691+0000] {processor.py:154} INFO - Started process (PID=473) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:37:09.722+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:37:09.725+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:37:09.725+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:37:22.008+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:37:22.006+0000] {__init__.py:492} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-b3n7k0y5 because the default path (/home/airflow/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-11-30T12:37:23.039+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:37:23.027+0000] {font_manager.py:1443} INFO - generated new fontManager
[2022-11-30T12:37:25.584+0000] {processor.py:766} INFO - DAG(s) dict_keys(['data_predict_dag']) retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:37:26.034+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:37:26.029+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2022-11-30T12:37:26.115+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:37:26.114+0000] {dag.py:3340} INFO - Setting next_dagrun for data_predict_dag to 2022-11-30T00:00:00+00:00, run_after=2022-12-01T00:00:00+00:00
[2022-11-30T12:37:26.162+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 16.570 seconds
[2022-11-30T12:38:02.077+0000] {processor.py:154} INFO - Started process (PID=509) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:38:02.142+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:38:02.222+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:38:02.213+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:38:32.627+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:38:32.604+0000] {timeout.py:68} ERROR - Process timed out, PID: 509
[2022-11-30T12:38:33.208+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:38:32.662+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 23, in <module>
    from pandas.compat.pyarrow import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/pyarrow.py", line 6, in <module>
    import pyarrow as pa
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 509
[2022-11-30T12:38:33.851+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:38:35.466+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dag_predict_proccess.py took 33.650 seconds
[2022-11-30T12:39:24.837+0000] {processor.py:154} INFO - Started process (PID=540) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:39:25.071+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:39:25.698+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:39:25.603+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:58:06.929+0000] {processor.py:154} INFO - Started process (PID=580) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:58:07.013+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T12:58:07.016+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:58:07.016+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T12:58:43.755+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:58:43.116+0000] {timeout.py:68} ERROR - Process timed out, PID: 580
[2022-11-30T12:58:52.402+0000] {logging_mixin.py:137} INFO - [2022-11-30T12:58:45.818+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 63, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1595, in init pandas._libs.tslibs.timedeltas
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1328, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 580
[2022-11-30T13:55:39.980+0000] {processor.py:154} INFO - Started process (PID=633) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T13:55:41.345+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T13:55:44.164+0000] {logging_mixin.py:137} INFO - [2022-11-30T13:55:43.857+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T13:57:22.199+0000] {processor.py:154} INFO - Started process (PID=681) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T13:57:23.871+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T13:57:24.482+0000] {logging_mixin.py:137} INFO - [2022-11-30T13:57:24.469+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T13:57:56.627+0000] {logging_mixin.py:137} INFO - [2022-11-30T13:57:55.413+0000] {timeout.py:68} ERROR - Process timed out, PID: 681
[2022-11-30T13:58:04.343+0000] {logging_mixin.py:137} INFO - [2022-11-30T13:57:57.859+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 681
[2022-11-30T13:58:08.938+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T13:59:06.573+0000] {processor.py:154} INFO - Started process (PID=722) to work on /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T13:59:07.050+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dag_predict_proccess.py for tasks to queue
[2022-11-30T13:59:08.112+0000] {logging_mixin.py:137} INFO - [2022-11-30T13:59:08.090+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dag_predict_proccess.py
[2022-11-30T13:59:41.430+0000] {logging_mixin.py:137} INFO - [2022-11-30T13:59:40.874+0000] {timeout.py:68} ERROR - Process timed out, PID: 722
[2022-11-30T13:59:48.053+0000] {logging_mixin.py:137} INFO - [2022-11-30T13:59:43.716+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dag_predict_proccess.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_predict_proccess.py", line 3, in <module>
    from packages.predicting_process import predictor
  File "/opt/airflow/dags/packages/predicting_process.py", line 1, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1396, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1354, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 606, in spec_from_file_location
  File "<frozen importlib._bootstrap>", line 372, in __init__
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/dag_predict_proccess.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.4.3/best-practices.html#reducing-dag-complexity, PID: 722
[2022-11-30T14:00:00.530+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_predict_proccess.py
