[2022-11-26T15:19:58.805+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_preparator_dag.data_prepare manual__2022-11-26T15:19:55.266771+00:00 [queued]>
[2022-11-26T15:19:58.836+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_preparator_dag.data_prepare manual__2022-11-26T15:19:55.266771+00:00 [queued]>
[2022-11-26T15:19:58.839+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T15:19:58.842+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-26T15:19:58.847+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T15:19:58.879+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): data_prepare> on 2022-11-26 15:19:55.266771+00:00
[2022-11-26T15:19:58.940+0000] {standard_task_runner.py:55} INFO - Started process 128 to run task
[2022-11-26T15:19:58.949+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_preparator_dag', 'data_prepare', 'manual__2022-11-26T15:19:55.266771+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_train_process.py', '--cfg-path', '/tmp/tmpzu_513_z']
[2022-11-26T15:19:58.953+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask data_prepare
[2022-11-26T15:19:59.073+0000] {task_command.py:376} INFO - Running <TaskInstance: data_preparator_dag.data_prepare manual__2022-11-26T15:19:55.266771+00:00 [running]> on host 18e45f209dfb
[2022-11-26T15:19:59.178+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_preparator_dag
AIRFLOW_CTX_TASK_ID=data_prepare
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T15:19:55.266771+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-26T15:19:55.266771+00:00
[2022-11-26T15:19:59.220+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-11-26T15:19:59.231+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=data_preparator_dag, task_id=data_prepare, execution_date=20221126T151955, start_date=20221126T151958, end_date=20221126T151959
[2022-11-26T15:19:59.283+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-26T15:19:59.361+0000] {taskinstance.py:2623} INFO - 1 downstream tasks scheduled from follow-on schedule check
