[2022-11-26T15:05:33.875+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_predict_dag.data_predict manual__2022-11-26T15:04:02.201621+00:00 [queued]>
[2022-11-26T15:05:33.886+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: data_predict_dag.data_predict manual__2022-11-26T15:04:02.201621+00:00 [queued]>
[2022-11-26T15:05:33.891+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T15:05:33.892+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-11-26T15:05:33.893+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-26T15:05:33.909+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): data_predict> on 2022-11-26 15:04:02.201621+00:00
[2022-11-26T15:05:33.922+0000] {standard_task_runner.py:55} INFO - Started process 20350 to run task
[2022-11-26T15:05:33.931+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_predict_dag', 'data_predict', 'manual__2022-11-26T15:04:02.201621+00:00', '--job-id', '498', '--raw', '--subdir', 'DAGS_FOLDER/dag_predict_proccess.py', '--cfg-path', '/tmp/tmpy3lbck2r']
[2022-11-26T15:05:33.935+0000] {standard_task_runner.py:83} INFO - Job 498: Subtask data_predict
[2022-11-26T15:05:34.003+0000] {task_command.py:376} INFO - Running <TaskInstance: data_predict_dag.data_predict manual__2022-11-26T15:04:02.201621+00:00 [running]> on host 3151441c8efc
[2022-11-26T15:05:34.049+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_predict_dag
AIRFLOW_CTX_TASK_ID=data_predict
AIRFLOW_CTX_EXECUTION_DATE=2022-11-26T15:04:02.201621+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-26T15:04:02.201621+00:00
[2022-11-26T15:05:34.140+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator MinMaxScaler from version 1.1.3 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,

[2022-11-26T15:05:34.153+0000] {logging_mixin.py:137} INFO - 0.693
[2022-11-26T15:05:34.154+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-11-26T15:05:34.164+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=data_predict_dag, task_id=data_predict, execution_date=20221126T150402, start_date=20221126T150533, end_date=20221126T150534
[2022-11-26T15:05:34.225+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-26T15:05:34.241+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
